version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: .docker/prod.Dockerfile
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    stdin_open: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - ${DOCKER_HTTP_PORT}:80
    networks:
      kwerio:
        ipv4_address: ${DOCKER_APP_IPV4}
    environment:
      APP_URL: ${APP_URL}
      DEBIAN_FRONTEND: noninteractive
      GROUP_ID: ${DOCKER_GROUP_ID}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TERM: xterm
      TZ: UTC
      USER_ID: ${DOCKER_USER_ID}
    command: /root/setup.sh

networks:
  kwerio:
    name: ${DOCKER_NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}
